import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navber from "./components/Navber";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navber></Navber>

        <main className="min-h-screen   max-w-7xl mx-auto ">
          {children}
        </main>

        
        <footer>
          <div className="flex justify-center items-center">
            <h1 className="text-orange-600  underline">Awasome</h1>
          </div>
        </footer>
      </body>
    </html>
  );
}
